### ISSUE TITLE
210318 텀블러

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#13]
앞전에 김소영주임이 조사하던 텀블러건 관련 내용전체 정리해서 댓글로 보고

**Comment by zione93** [comment]
http://domeggook.com/7251639


**- 따로구매 가능, 따로구매시 가격**
ㅁ 보틀
아이스보틀 1개당 1350원 / 트라이탄 1개당 1890원
** 100개 이상 구매 시, 100개 이하 구매 시 가격변동없이
개당 가격으로 계산.

ㅁ 파우치
파우치 100개 미만 구매시 750원 /  100개 이상구매시 600원까지 가능
색상은 그레이랑 블루가 있음.

**- 같이구매**
아이스보틀+파우치 2100원 100개 이상구매시 100개 미만구매시 동일한가격
트라이탄보틀+파우치 2640원 100개 이상구매시 100개 미만구매시 동일한가격  
300개 이상 주문시 30원에서 50원 할인 적용.

**- 같이구매, 따로 구매 시 동일하게 적용되는 내용**
100개 이상 구매시 인쇄, 포장 무료.
뚜껑색상 3가지 정도 가능, 랜덤으로 색상 선택 가능
텍스트 색상은 인쇄할 경우 한가지만 선택가능.
텍스트 색상은 1개 추가시 개당 110원이 부가


**- 조사에서 빠졌던 부분**
1. 텀블러 뚜껑색상 3가지 정도 가능하다고 했는데 랜덤으로 색상이 가능하다는 뜻인지, 내가 고른 3가지 색상에서 
갯수가 랜덤이란 뜻인지 의미가 불명확
> 주문을 할 때 우리가 색상 선택 가능 / 주문자가 색상별 제품 갯수 선택 가능합니다.

2. 100개 구입시 멘트또한 3가지로 제작이 가능한지 부분에 대한 답
> 시안은 1가지가 기본입니다. 여러가지 시안으로 한다면 1시안당 22000원 추가(부가세포함된금액) 
100개 구매시 만약 3멘트를 한다면? ex)고마워30개 기다릴게30개 안녕40개 > 총 인쇄비용 66000원 추가 발생 
100개 구매시 1멘트를 한다면? ex) 기다릴게100개 > 인쇄비용무료  
300개 구매시 3가지 멘트 무료 

3. 트라이탄이 냉온 다 되는 걸로 알고있는데 이 제품이 맞다면 트라이탄으로 견적을 내고 300개시 정확하게  
30원 할인인지, 50원 할인인지에 대해 알아야 하고, 부가세 포함인지 미포함인지
> 트라이탄 냉온 다됩니다.
> 트라이탄 300개 이상 구매시 한 개당 1890원에서 1750원까지 내고가능 
네오파우치 300개 이상 구매시 750원에서 650원까지 내고가능
트라이탄 + 네오파우치 300개 이상 구매시 2640원에서 2400원까지 내고가능 (모두 부가세 포함된금액)  

4. 텀블러 중국산인지 국내산인지에 대한 확답
> 텀블러 국내산이라고 답변 받았습니다.

**Comment by hwconverge** [comment]
3번 기준으로 계산시 인쇄무료에 뚜껑 3가지 선택가능한건가???

**Comment by zione93** [comment]
네 맞습니다
