### ISSUE TITLE
210319 태성상 제품확인 

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#15]
네이트온 준거 참고

**Comment by zione93** [comment]
https://smartstore.naver.com/attackzone/products/4974659208
https://smartstore.naver.com/attackzone/products/4976520463
https://smartstore.naver.com/attackzone/products/4976313761

3가지 제품 모두 주문 가능하며, 두건은 상세에서 원 안에 있는 제품 색상이 맞다고 하십니다.
실제 제품 사진 같이 첨부드립니다

![KakaoTalk_20210319_100838200](https://user-images.githubusercontent.com/68890865/111744290-54116a00-88ce-11eb-859e-e39045143f5e.jpg)
