### ISSUE TITLE
210322 텀블러 문구

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#17]
각자 텀블러에 들어갈 문구 10개씩

문구형태 디자인은 팀장통해서 확인

**Comment by zione93** [comment]
- 너와 함께한 순간들이 행복했고,
앞으로도 행복할거야

- 내 옆에 있어줘서
고맙고 사랑해

- 너의 시간 속에
늘 내가 있을게

- 전역할때까지 매일매일
예쁘게 기다릴게

- 수분 충전하고
오늘 하루도 화이팅

- 서로 변함없이
사랑해주자

- Near and Dear

- 마시면서 내 생각하기

- 넌 내가 살아숨쉬는 이유야

- 내가 있기에 너가 있고,
너가 있기에 내가 있어

- 그리운 건 그 때일까, 그대일까

- 정말로 사랑한다면 기다려주세요

- 2년 뒤 멋진 모습으로 나타날게

- 불안해 하지마 난 너만 볼게

- 모든 날씨마다 너 생각

- 오늘도 니가 그립다는 뻔한 말

- 그대를 기다린다는 것

- 언제나 이 곳에 있을게

- 바람꽃이 되어 기다린다

**Comment by hwconverge** [comment]
1.넌 나라를 지키고 난 너를 지킨다
2.우리 아들 고맙고 사랑해
3.고마워 사랑해줘서
4.마셔라 살기위해서
5.세상에 최소한 내편 하나가 있다는것을 잊지말자 
6.병처럼 깨질지언정 깡통처럼 찌그러지지 않는다
7.널 사랑하는 모든이가 널 응원해 NEVER GIVE UP
8. 날죽이지 못하는 고통은 날 더 강하게 만든다
9. 넌 혼자가 아니야 널 사랑하는 우리가 있잖아
10. 울지마라 항상 널 응원한다
11. 포기하지마라 난 널 믿는다
12. 손들어 물쏜다
13. 오늘도 내 손잡았네
14. 제발 전화받던지 전화하던지
15. 내마음이 너에게 닿기를
16 .사랑은 언제나 목마르다
17.당신의 마음이 늘 내마음과 같으면 좋겠습니다
18.오래도록 당신을 기다렸습니다
19.이별이 두려워 사랑하지 못하는자는 죽음이 두려워 숨쉬지 못하는자와 같다

**Comment by kimdonghyeon1111** [comment]
[텀블러 문구 선정] 김동현
1. 모든 날씨마다 네 생각
2. 내 마음이 너에게 닿기를
3. 너의 시간 속에 늘 내가 있을게
입니다.

**Comment by zione93** [comment]
1. 세상에 최소한 내편 하나가 있다는것을 잊지말자
2. 불안해 하지마 난 너만 볼게
3. 사랑은 언제나 목마르다
