### ISSUE TITLE
210319 요이치 제품문의

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#18]
https://smartstore.naver.com/yoitch/search?q=%EC%9D%BC%EC%B2%B4%ED%98%95%EC%B6%A9%EC%A0%84%EA%B8%B0&st=REVIEW&free=false&dt=LIST&page=1&size=40

요이치 쪽 전화해서 도매문의
1.5핀 8핀 c타입 그리고 고속형까지 현재 우리꺼랑 똑같이물어보고
박스단위로 아마 거래될건데 몇박스일경우 금액이 더 떨어지는지물어봐주세요

**Comment by zione93** [comment]
200개 이상 주문시
5핀 개당 2,200원 / C타입, 8핀 2,500원 / 고속 (라울 c타입) 4,500원
(부가세 포함 가격입니다)

* 8핀은 현재 재고 없다고 하십니다.
* 200개 이하는 도매가 알려주시지 않는다고 하셨고, 많이 산다고 할인이 되는 부분은 없다고 하셨습니다.
* 온라인판매는 도매로 따로 진행하고 계시지 않다고 하셨습니다.
