### ISSUE TITLE
210322 택배 부분

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#19]
스토어팜 보니 반품택배가 아직도 씨제이~ 우체국으로 당장교체 바로보고

그외에 샵도 모두 우체국 여부 확인 보고

**Comment by zione93** [comment]
스토어팜 기본 택배사 우체국으로 변경 완료했습니다

**Comment by zione93** [comment]
다른 샵은 기본 택배사를 정하는 게 아닌, 반품지를 따로 등록하는 부분입니다.
쿠팡은 반품지 수정되어 있으며, 다른 쇼핑몰은 주소지 수정 서류 필요합니다.

**Comment by hwconverge** [comment]
서류는 오늘 준비해서 줄것임 이부분 나한데 다시한번 확인하길 바랍니다

**Comment by hwconverge** [comment]
해당 부분 결과 보고

**Comment by zione93** [comment]
- 스토어팜 : 소재지 변경 완료
- 아이디어스 : 소재지 변경 완료
- 쿠팡 : 소재지 변경 완료 및 반품지 변경 완료
- 톡스토어 : 소재지 변경 검수 진행 중 (3/31) / 출고지 및 반품지는 수정 완료 되었습니다
- 위메프 : 소재지 변경 검수 진행 중 (3/31) / 출고지 및 반품지는 수정 완료 되었습니다
- 에이블리 : 소재지 변경 완료 및 반품지 변경 완료

**Comment by hwconverge** [comment]
반품지도 확인 스토어팜 보니 반품지가 덕포동으로 나옴 이부분들 모두 체크후 별도 보고
