### ISSUE TITLE
210331 쿠팡 썸네일 수정건

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#27]
쿠팡도 곰신톡프렌즈 썸네일 캐릭터들어간것처럼 썸네일 부분에 군대캐릭터 삽입
보조배터리,입대용품등 내가 현재까지 팀장한데 요청한 부분만. 적용후 보고

**Comment by zione93** [comment]
군화끈조임이, 보조배터리, 이니스프리 3종, 시계세트 썸네일 수정했습니다
