### ISSUE TITLE
재고파악

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#3]
현재 부족한 재고들 파악해서 보고할것

**Comment by zione93** [comment]
1. 뽁뽁이
2. 편지 포장 비닐 (가로 16cm x 세로 23cm)
3. 잘라서 쓰는 큰 골판지

부족한 재고 보고드립니다

**Comment by hwconverge** [comment]
1.뽁뽁이 큰거는 추후주문할거니 좀더 지켜보고 다시 요청
2.완료
3.완료
