### ISSUE TITLE
210406 쓱 가입

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#31]
https://partners.ssgadm.com/

쓱 파트너 가입후 상품 1개 테스트로 업로드

**Comment by zione93** [comment]
http://po.ssgadm.com/

가입완료 했습니다 편지지 1탄 올라가있습니다
ID : hwconverge2
PW : Gusdntldn23!

**Comment by hwconverge** [comment]
쓱 브랜드 검색 부분 신청은 일단 내가 처리함

**Comment by zione93** [comment]
비밀번호는 설정 조건때문에 기존 쓰던 비밀번호가 안됩니다 (ex. 대문자가 포함되어야 함, 비밀번호 길이제한)
기본설정 부분 완료 후 다시 보고드리겠습니다

**Comment by hwconverge** [comment]
비번 부분은 확인 기본설정 완료후 보고 ~

**Comment by zione93** [comment]
http://www.ssg.com/sellerhome/gomsintalk
기본설정 완료했습니다
