### ISSUE TITLE
210416 팀원 업무 분담 기획안

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#37]
현재 팀원 업무 분담 부분 내용 정리해서 팀장이 직접 보고
업무분담 내용은 기본업무만 포함 프로젝트 내용은 별도 보고 하지 않음

ex)
팀장
1.팀원관리
2.업무분배
3.구매관리
4.계약관리
5.웹디자인 및 코딩

김주임
1.택배 완포
2.영상 제작
3.편지 파트 담당
4.스마트스토어

허주임
1.캐릭터 제작
2.스티커 파트 담당
3.쿠팡

??사원
1.cs처리
2.카카오 쇼핑
3.전체 샵 상담업무?

위에 예시는 그냥 예시임 파트 분담 부분 4월16일까지 반드시 보고

**Comment by zione93** [comment]
카톡으로 파일 전달드렸습니다
