### ISSUE TITLE
210319 쿠팡 입대용품

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#4]
쿠팡 입대용품 부분 금요일까지 완료

키워드 부분,타이틀 부분 반드시 네이버스토어와 동일하게 작업!

가격 부분 다시 한번체크 옵션 주의!!

**Comment by hwconverge** [comment]
쿠팡 입대용품 보고!!

**Comment by zione93** [comment]
현재 업로드 안된 제품

- 군인양말 (동계용)
- 요술장갑
- 요술덧신
- 귀마개
- 넥워머
- 실리콘공병
- 바르는 기피제
- 뿌리는 기피제
- 면봉

입니다.

**Comment by hwconverge** [comment]
쿠팡 안올라간거 언제 올라가는지 보고??
