### ISSUE TITLE
210409 오후2시까지 군스타조사 1차조사

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#40]
1차로 5명 조사

자칭 연예인 또는 스타라고 불리는 사람들 군입대한 기록 조사
반드시 네이버에서 인물검색에 나오는 사람만 가능
군입대 날짜 확정된 인물 또는 군복무중인 사람만 해당

군별:
네이버검색시 이름:
입대일자:

**Comment by zione93** [comment]
- 펜타곤 후이
군별 : 공익
네이버 검색시 이름 : 후이
입대일자 : 2021.02.18

- 펜타곤 진호
군별 : 육군
네이버 검색시 이름 : 진호
입대일자 : 2020.05.11

- 인피니트 엘
군별 : 해병대
네이버 검색시 이름 : 김명수 (엘)
입대일자 : 21.02.22

- 데이식스 성진
군별 : 육군
네이버 검색시 이름 : 성진
입대일자 : 2021.03.08

- 박보검
군별 : 해군
네이버 검색시 이름 : 박보검
입대일자 : 2020.08.31

- 우도환
군별 : 육군
네이버 검색시 이름 : 우도환
입대일자 : 2020.07.06

- 엑소 찬열
군별 : 육군
네이버 검색시 이름 : 찬열
입대일자 : 2021.03.29

- 엑소 백현
군별 : 공익
네이버 검색시 이름 : 백현
입대일자 : 2021.05.06 입대 예정

- 엑소 수호
군별 : 공익
네이버 검색시 이름 : 수호
입대일자 : 2020.05.14

- 비투비 정일훈
군별 : 공익
네이버 검색시 이름 : 정일훈
입대일자 : 2020.5.28

- 비투비 육성재
군별 : 육군
네이버 검색시 이름 : 육성재
입대일자 : 2020.05.11

- 비투비 임현식
군별 : 육군
네이버 검색시 이름 : 임현식
입대일자 : 2020.05.11

군입대 조사입니다

**Comment by zione93** [comment]
올해 입대 예정 - 가수 비와이, 샤이니 태민, 위너 송민호, 빅스 라비, 블락비 피오, 방탄 소년단 슈가, 몬스타엑스 기현, 몬스타엑스 민혁, 배우 서강준, 틴탑 - 리키(육군), 몬스타 엑스 셔누, 배우 장기용, 배우 송강

**Comment by hwconverge** [comment]
현재 조사된 군인 안이사님한데 공유해서 이부분 처리 안이사님한데 어떤부분 준비해서 처리하면되는지 물어보고 해당 연예인들 적용 아울러 공익이란 말은 현재는 없다 정확하게 사회복무요원인지 다른명칭인지 확인필요
