### ISSUE TITLE
210420 버블디 대표 디자인전달

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#60]
버블디 대표한데 디자인 전달 및 커뮤케이션
이후 상황 보고

**Comment by zione93** [comment]
- 네이티브 영역
아이콘 이미지 사이즈 3x 사이즈로 전달 요청 하셨습니다

- 상단바, 위젯
이번 일정에는 힘들다고 하셨고, 상단바는 리엑트네이티브로 다시 만들어야 된다고 하셨습니다. 이후 위젯 시안 따로 나와야 된다고 하셨습니다.

**Comment by zione93** [comment]
요청하신 아이콘 및 수정 시안 파일 전달 완료했습니다
아이콘 및 로고는 변경하려면 앱 업데이트를 해야 진행 가능하다고 하셔서 수정해서 다시 전달드린다고 말씀드려놓은 상태입니다

**Comment by zione93** [comment]
- 하단 메뉴 변경 아이콘 전달 및 확인 완료 되었습니다 (4/23)
- 로고 변경 아이콘 전달 완료 되었습니다 (4/26)
