### ISSUE TITLE
210317 썸네일수정건

### ISSUE THREAD

**Issue by hwconverge** [zione93/hwconverge#9]
기존 상품 썸네일에 육군 캐릭터 넣은것처럼 뽀뽀이미지 이부분으로

위장크림세트 부분에 썸네일 넣어서 바로 보내주세요

**Comment by zione93** [comment]
![00_썸네일_합성본](https://user-images.githubusercontent.com/68890865/111453921-6c12ad80-8757-11eb-94e9-5913ce695dcb.png)

카톡으로 파일 전달드렸습니다

**Comment by hwconverge** [comment]
별도 말이 없을경우는 무조건 육군으로 ~ 파일 다시 카톡으로 육군

**Comment by zione93** [comment]
![00_썸네일_합성본](https://user-images.githubusercontent.com/68890865/111554115-0d861780-87c9-11eb-8f07-c3cfeaebd66d.png)

썸네일 수정입니다

**Comment by hwconverge** [comment]
확인!
